### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by chuckyz** [mimuret/dtap#11]
Hello @mimuret I would like to utilize this code more extensively but I require a license to do so.

Would you be comfortable accepting an Apache License 2.0 PR?  This means folks are quite free to do what they wish to do with the code and protects contributors at the same time.

**Comment by mimuret** [comment]
This software is released under the Apache 2.0 license.
I completely forgot to add the license file.
Already merge it. #12

**Comment by chuckyz** [comment]
Thank you!!
